server:
  port: 8888

eureka:
  client:
    # 需要指向eureka注册中心的地址
    service-url:
      defaultZone: http://10.22.3.10:8801/eureka/, http://10.22.3.10:8802/eureka/
  instance:
    appname: mainservice

spring:
  application:
    name: mainservice
