server:
  port: 8801
eureka:
  client:
    # 不需要从eureka获取注册信息
    fetch-registry: true
    # 将自己注册到eureka
    register-with-eureka: true
    # 需要指向eureka注册中心的地址
    service-url:
      defaultZone: http://master02:8802/eureka
  instance:
    ip-address: 10.22.8.78
    hostname: master

spring:
  application:
    name: master
#  cloud:
#    inetutils:
#      preferred-networks: 10.22.8.78