spring:
  application:
    name: productservice

springdoc:
  api-docs:
    enabled: true
eureka:
  client:
    # 需要指向eureka注册中心的地址
    service-url:
      defaultZone: http://10.22.8.78:8801/eureka/, http://10.22.8.78:8802/eureka/
  instance:
    appname: productservice