eureka:
  client:
    serviceUrl:
      defaultZone: http://10.22.3.10:8801/eureka/, http://10.22.3.10:8802/eureka/
  instance:
    appname: configservice

server:
  port: 7777
spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Spring-Project/cloud/config
          default-label: config