eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.5.1:8801/eureka/, http://192.168.5.1:8802/eureka/
  instance:
    appname: configservice

server:
  port: 7777
spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cockmake/SpringCloudStudy.git
          default-label: config